apiVersion: v1
kind: Namespace
metadata:
  name: fedfina-s
---
# Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fedfina-backend
  namespace: fedfina-s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fedfina-backend
  template:
    metadata:
      labels:
        app: fedfina-backend
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: backend
          image: docker.io/docker4zerocool/fedfina-backend:main-110f67f
          ports:
            - containerPort: 8000
          env:
            - name: ENV
              value: "staging"
            - name: API_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: fedfina-secrets
                  key: api-secret-key
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: fedfina-secrets
                  key: database-url
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: fedfina-secrets
                  key: openai-api-key
            - name: ELEVENLABS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: fedfina-secrets
                  key: elevenlabs-api-key
            - name: ELEVENLABS_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: fedfina-secrets
                  key: elevenlabs-webhook-secret
            - name: MINIO_ENDPOINT
              value: "minio-service:9000"
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: fedfina-secrets
                  key: minio-access-key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: fedfina-secrets
                  key: minio-secret-key
            - name: SMTP_SERVER
              valueFrom:
                secretKeyRef:
                  name: fedfina-secrets
                  key: smtp-server
            - name: SMTP_PORT
              value: "587"
            - name: SMTP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: fedfina-secrets
                  key: smtp-username
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fedfina-secrets
                  key: smtp-password
            - name: SMTP_FROM_EMAIL
              valueFrom:
                secretKeyRef:
                  name: fedfina-secrets
                  key: smtp-from-email
            # Timezone Configuration for IST
            - name: DEFAULT_TIMEZONE
              valueFrom:
                secretKeyRef:
                  name: fedfina-secrets
                  key: default-timezone
            - name: TIMEZONE_OFFSET_HOURS
              valueFrom:
                secretKeyRef:
                  name: fedfina-secrets
                  key: timezone-offset-hours
            - name: TIMEZONE_OFFSET_MINUTES
              valueFrom:
                secretKeyRef:
                  name: fedfina-secrets
                  key: timezone-offset-minutes
            - name: BUSINESS_START_HOUR
              valueFrom:
                secretKeyRef:
                  name: fedfina-secrets
                  key: business-start-hour
            - name: BUSINESS_END_HOUR
              valueFrom:
                secretKeyRef:
                  name: fedfina-secrets
                  key: business-end-hour
            - name: ENABLE_IST_TIMEZONE
              valueFrom:
                secretKeyRef:
                  name: fedfina-secrets
                  key: enable-ist-timezone
            - name: SHOW_TIMEZONE_INFO
              valueFrom:
                secretKeyRef:
                  name: fedfina-secrets
                  key: show-timezone-info
            - name: DISABLE_EMAIL_SENDING
              valueFrom:
                secretKeyRef:
                  name: fedfina-secrets
                  key: disable-email-sending
            # Redis Configuration
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: fedfina-secrets
                  key: redis-url
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
---
# Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fedfina-frontend
  namespace: fedfina-s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fedfina-frontend
  template:
    metadata:
      labels:
        app: fedfina-frontend
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: frontend
          image: docker.io/docker4zerocool/fedfina-frontend:main-fea6f13
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_API_URL
              value: "http://staging.fedfina-s.bionicaisolutions.com/api"
            - name: REACT_APP_ENV
              value: "staging"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
---
# Backend Service
apiVersion: v1
kind: Service
metadata:
  name: fedfina-backend
  namespace: fedfina-s
spec:
  selector:
    app: fedfina-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
---
# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: fedfina-frontend
  namespace: fedfina-s
spec:
  selector:
    app: fedfina-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
---
# Internal Ingress for staging
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fedfina-staging-ingress
  namespace: fedfina-s
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
spec:
  rules:
    - host: staging.fedfina-s.bionicaisolutions.com
      http:
        paths:
          # Frontend routes
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fedfina-frontend
                port:
                  number: 3000
          # Backend API routes
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: fedfina-backend
                port:
                  number: 8000
