apiVersion: v1
kind: Namespace
metadata:
  name: fedfina
---
# Secrets
apiVersion: v1
kind: Secret
metadata:
  name: fedfina-secrets
  namespace: fedfina
type: Opaque
data:
  # Base64 encoded values - these should be managed externally
  api-secret-key: ZGV2ZWxvcG1lbnQtc2VjcmV0LWtleS1jaGFuZ2UtaW4tcHJvZHVjdGlvbg==
  database-url: cG9zdGdyZXNxbDovL2ZlZGZpbmE6ZmVkZmluYVRoMTUxNVQwcDUzY3IzdEBwZy1ydy5wb3N0Z3Jlcy5zdmMuY2x1c3Rlci5sb2NhbDo1NDMyL2ZlZGZpbmE=
  openai-api-key: c2stcHJvai1MUm1CN3lKbkFSWFowSlBITjJ5Z29rODlHaVVFV0JDNDVYLUNEY2ZCRGxXOWV4WW5Bb2tvdnF0OURLcVFFS2R5Q3gwNEN2bnpHdFQzQmxia0ZKX0NPLXpmS1BVZ2VwTDd6T0h0elhzR1ExREY5Y3FwU2pMaDhhUDhBNEF4V2RFUm00dmYtd0NMbUpUT0NFYTBCclMwSFZSX2dYVUE=
  elevenlabs-api-key: c2tfZTkwNjNjMmI4MDNlZjY3YjNiNTBkNjk2YWI1NDA5YTZhNzAyNzMyMjkxYzBjZjY0
  elevenlabs-webhook-secret: d3NlY19kYWNhMTc2NDBkMGIwYzA2NzAxMTc5MWZmZjBjYmRmYTRkMDRhNTExMTBmZTlhZjJmYzEyNTZjMTc3MDZmZjA2
  minio-access-key: YWNjZXNzLWFsbC1idWNrZXRz
  minio-secret-key: MEtsaGwrQzVkL1VzdVpxQUNxRWlDNGp3Nm16bEJodGU=
  minio-endpoint: bWluaW8taGwubWluaW8uc3ZjLmNsdXN0ZXIubG9jYWw6OTAwMA==
  smtp-server: c210cC5nbWFpbC5jb20=
  smtp-port: NDY1
  smtp-username: U2FsaWwuS2FkYW1AZ21haWwuY29t
  smtp-password: cHN1bnd1cWp1aXZraXJwcg==
  smtp-from-email: U2FsaWwuS2FkYW1AZ21haWwuY29t
  smtp-use-tls: dHJ1ZQ==
  redis-url: cmVkaXM6Ly86VGgxNTE1VDBwNTNjcjN0QHJlZGlzLnJlZGlzLnN2Yy5jbHVzdGVyLmxvY2FsOjYzNzk=
  callback-enabled: ZmFsc2U=
  callback-timeout-seconds: MzA=
  callback-url: aHR0cHM6Ly9oci5mZWRmaW5hLmNvbS9zYWxlc3BkL2FwaS9zYXZlVm9pY2VQRA==
---
# Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fedfina-backend
  namespace: fedfina
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fedfina-backend
  template:
    metadata:
      labels:
        app: fedfina-backend
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: backend
          image: docker.io/docker4zerocool/fedfina-backend:main-d03c193
          ports:
            - containerPort: 8000
          env:
            - name: ENV
              value: "production"
            - name: API_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: fedfina-secrets
                  key: api-secret-key
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: fedfina-secrets
                  key: database-url
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: fedfina-secrets
                  key: openai-api-key
            - name: ELEVENLABS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: fedfina-secrets
                  key: elevenlabs-api-key
            - name: ELEVENLABS_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: fedfina-secrets
                  key: elevenlabs-webhook-secret
            - name: MINIO_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: fedfina-secrets
                  key: minio-endpoint
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: fedfina-secrets
                  key: minio-access-key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: fedfina-secrets
                  key: minio-secret-key
            - name: SMTP_SERVER
              valueFrom:
                secretKeyRef:
                  name: fedfina-secrets
                  key: smtp-server
            - name: SMTP_PORT
              valueFrom:
                secretKeyRef:
                  name: fedfina-secrets
                  key: smtp-port
            - name: SMTP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: fedfina-secrets
                  key: smtp-username
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fedfina-secrets
                  key: smtp-password
            - name: SMTP_FROM_EMAIL
              valueFrom:
                secretKeyRef:
                  name: fedfina-secrets
                  key: smtp-from-email
            - name: SMTP_USE_TLS
              valueFrom:
                secretKeyRef:
                  name: fedfina-secrets
                  key: smtp-use-tls
            - name: CALLBACK_ENABLED
              valueFrom:
                secretKeyRef:
                  name: fedfina-secrets
                  key: callback-enabled
            - name: CALLBACK_URL
              valueFrom:
                secretKeyRef:
                  name: fedfina-secrets
                  key: callback-url
            - name: CALLBACK_TIMEOUT_SECONDS
              valueFrom:
                secretKeyRef:
                  name: fedfina-secrets
                  key: callback-timeout-seconds
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: fedfina-secrets
                  key: redis-url
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
---
# Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fedfina-frontend
  namespace: fedfina
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fedfina-frontend
  template:
    metadata:
      labels:
        app: fedfina-frontend
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: frontend
          image: docker.io/docker4zerocool/fedfina-frontend:main-4db18dd
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_API_URL
              value: "https://fedfina.bionicaisolutions.com/api"
            - name: REACT_APP_ENV
              value: "production"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
---
# Backend Service
apiVersion: v1
kind: Service
metadata:
  name: fedfina-backend
  namespace: fedfina
spec:
  selector:
    app: fedfina-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
---
# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: fedfina-frontend
  namespace: fedfina
spec:
  selector:
    app: fedfina-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
---
# Ingress for fedfina.bionicaisolutions.com with Let's Encrypt SSL
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fedfina-ingress
  namespace: fedfina
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "false"
spec:
  tls:
  - hosts:
    - fedfina.bionicaisolutions.com
    secretName: fedfina-tls
  rules:
    - host: fedfina.bionicaisolutions.com
      http:
        paths:
          # Frontend routes
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fedfina-frontend
                port:
                  number: 3000
          # Backend API routes
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: fedfina-backend
                port:
                  number: 8000

