name: CI/CD - Build and Deploy to Kubernetes via ArgoCD

on:
  push:
    branches: [main]

env:
  REGISTRY: docker.io
  IMAGE_NAME: docker4zerocool/fedfina
  NAMESPACE: fedfina
  APP_NAME: eleven
  DOMAIN: fedfina.bionicaisolutions.com

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Update k8s manifests with new image tag
        run: |
          sed -i "s|image: .*$|image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}|" frontend/deploy/deployment.yaml

      - name: Commit and push updated manifests
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update image tag to ${{ github.sha }} [ci skip]"
          branch: main
          file_pattern: 'frontend/deploy/deployment.yaml'

  # ArgoCD will auto-sync the updated manifests from the repo 